aruco_eef_tracker_node:
  ros__parameters:
    image_topic: /eef_camera/image_raw
    camera_info_topic: /eef_camera/camera_info

    pose_topic: /target/aruco_pose
    visible_topic: /target/aruco_visible
    status_topic: /target/aruco_status
    debug_image_topic: /target/aruco_debug_image

    marker_id: 0
    accept_any_marker: false
    allowable_marker_ids: [0, 1]
    marker_size_m: 0.05
    dictionary: DICT_APRILTAG_36h11

    publish_debug_image: true
    draw_axes: true
    axis_length_m: 0.03
    status_period_s: 0.5

    min_marker_perimeter_px: 8.0
    max_reprojection_error_px: 12.0
    pose_z_min_m: 0.02
    pose_z_max_m: 2.00